### PR TITLE
flask_iiif: iiif url context template

### PR DESCRIPTION
**Pull request by drjova**
* Improves PEP8 syntax.

* NEW Adds `iiif_image_url` context function template.

Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by jirikuncar** [comment]
It's not necessary to use `BETTER` keyword for internal messages.

**Comment by drjova** [comment]
ok :) thanks!

**Comment by jirikuncar** [comment]
@drjova can you add more tests as you are adding new functions?

**Comment by jirikuncar** [comment]
@drjova please note that there are some issues with tests on Python 2.6. Can you have a look?

**Comment by drjova** [comment]
Indeed, should be fine now thanks!

**Pull request merged**
